set(_CATKIN_CURRENT_PACKAGE "pitt_geometric_tracking")
set(pitt_geometric_tracking_MAINTAINER "Buoncompagni Luca <luca.buoncompagni@edu.unige.it>")
set(pitt_geometric_tracking_DEPRECATED "")
set(pitt_geometric_tracking_VERSION "1.0.0")
set(pitt_geometric_tracking_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "libpcl-all-dev" "pcl_conversions" "pitt_object_table_segmentation" "sensor_msgs" "pcl_msgs" "pitt_msgs")
set(pitt_geometric_tracking_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime" "message_generation" "libpcl-all" "pcl_conversions" "pitt_object_table_segmentation" "sensor_msgs" "pcl_msgs" "pitt_msgs")
set(pitt_geometric_tracking_BUILDTOOL_DEPENDS "catkin")